dog_walks/dog_walks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from dog_walks.exception_handlers import page_not_found_handler, custom_handler500, permission_denied_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dog_walks.common.urls')),
    path('places/', include('dog_walks.places.urls')),
    path('accounts/', include('dog_walks.accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

handler404 = page_not_found_handler
handler500 = custom_handler500
handler403 = permission_denied_handler


dog_walks/dog_walks/places/models.py
from django.contrib.auth import get_user_model
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


from dog_walks.core.validators import only_cyrillic_letters_validator, OptionalSchemeURLValidator
from dog_walks.places.choices import NightsType, FoodPlacesType, PriceRange, \
    WalkType, WelcomeDog, Difficulty, District

UserModel = get_user_model()


class BasePlaceModel(models.Model):
    NAME_MAX_LENGTH = 100
    CITY_MAX_LENGTH = 50

    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
    )
    district = models.CharField(
        choices=District.choices(),
        max_length=District.max_len(),
    )
    city = models.CharField(
        max_length=CITY_MAX_LENGTH,
        validators=[only_cyrillic_letters_validator]
    )
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField()
    website = models.URLField(
        null=True,
        blank=True,
        validators=[OptionalSchemeURLValidator]
    )
    modified_date = models.DateField(
        auto_now=True,
    )
    user = models.ForeignKey(
        UserModel,
        on_delete=models.SET('Несъществуващ'),
    )
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ['longitude', 'latitude']
        abstract = True

    def unique_error_message(self, model_class, unique_check):
        if model_class == type(self) and unique_check == ('longitude', 'latitude'):
            return 'Вече има място на тези координати'
        else:
            return super(BasePlaceModel, self).unique_error_message(model_class, unique_check)


class Night(BasePlaceModel):
    PLACE_TYPE = 'night'
    type = models.CharField(
        choices=NightsType.choices(),
        max_length=NightsType.max_len(),
    )
    price = models.CharField(
        choices=PriceRange.choices(),
        max_length=PriceRange.max_len(),
    )

    beds_count = models.PositiveIntegerField()

    image = models.ImageField(
        upload_to='nights-places'
    )
    phone = PhoneNumberField()
    dog_fee = models.BooleanField(
        default=False,
    )


class Eat(BasePlaceModel):
    PLACE_TYPE = 'eat'

    type = models.CharField(
        choices=FoodPlacesType.choices(),
        max_length=FoodPlacesType.max_len(),
    )
    price = models.CharField(
        choices=PriceRange.choices(),
        max_length=PriceRange.max_len(),
    )
    image = models.ImageField(
        upload_to='eat-places'
    )
    phone = PhoneNumberField(
        null=True,
        blank=True,
    )


class Walk(BasePlaceModel):
    HOLIDAYS_MAX_LENGTH = 50
    PLACE_TYPE = 'walk'

    type = models.CharField(
        choices=WalkType.choices(),
        max_length=WalkType.max_len(),
    )

    dogs_are_welcome = models.CharField(
        choices=WelcomeDog.choices(),
        max_length=WelcomeDog.max_len(),
    )

    entrance_fee = models.BooleanField(
        default=False,
    )
    holidays = models.CharField(
        null=True,
        blank=True,
        max_length=HOLIDAYS_MAX_LENGTH,
    )
    duration = models.TimeField(
        null=True,
        blank=True,
        auto_now=False,
        auto_now_add=False,
    )
    distance = models.FloatField(
        null=True,
        blank=True,
    )
    displacement = models.FloatField(
        null=True,
        blank=True,
    )
    difficulty = models.CharField(
        choices=Difficulty.choices(),
        max_length=Difficulty.max_len(),
    )
    image = models.ImageField(
        upload_to='walk-places'
    )
    phone = PhoneNumberField(
        null=True,
        blank=True,
    )

dog_walks/dog_walks/places/forms.py
from django import forms
from dog_walks.core.utils import field_required_error
from dog_walks.places.models import Night, Eat, Walk

class CreateNightsPlaceForm(forms.ModelForm):
    class Meta:
        model = Night
        exclude = ('approved', 'user')
        labels = {
            'name': 'Име',
            'district': 'Област',
            'city': 'Населено място',
            'latitude': 'Географска ширина',
            'longitude': 'Географска дължина',
            'description': 'Описание',
            'website': 'Уебсайт',
            'type': 'Вид',
            'price': 'Ценови Диапазон',
            'beds_count': 'Брой места за настаняване',
            'phone': 'Телефон за връзка',
            'image': 'Снимка',
            'dog_fee': 'Допълнително заплащане за куче',
        }

    def __init__(self, *args, **kwargs):
        super(CreateNightsPlaceForm, self).__init__(*args, **kwargs)
        field_required_error(self.fields.values())


class CreateEatPlaceForm(forms.ModelForm):
    class Meta:
        model = Eat
        exclude = ('approved', 'user')
        labels = {
            'name': 'Име',
            'district': 'Област',
            'city': 'Населено място',
            'latitude': 'Географска ширина',
            'longitude': 'Географска дължина',
            'description': 'Описание',
            'website': 'Уебсайт',
            'price': 'Ценови Диапазон',
            'type': 'Вид',
            'image': 'Снимка',
            'phone': 'Телефон за връзка',
        }

    def __init__(self, *args, **kwargs):
        super(CreateEatPlaceForm, self).__init__(*args, **kwargs)
        field_required_error(self.fields.values())


class CreateWalkPlaceForm(forms.ModelForm):
    class Meta:
        model = Walk
        exclude = ('approved', 'user')
        labels = {
            'name': 'Име',
            'district': 'Област',
            'city': 'Населено място',
            'latitude': 'Географска ширина',
            'longitude': 'Географска дължина',
            'description': 'Описание',
            'website': 'Уебсайт',
            'type': 'Категория',
            'dogs_are_welcome': 'Допускане на кучета',
            'image': 'Снимка',
            'entrance_fee': 'Такса за вход',
            'holidays': 'Почивни дни',
            'duration': 'Времетраене',
            'distance': 'Разстояние в километри',
            'displacement': 'Дениевлация в метри',
            'difficulty': 'Трудност',
            'phone': 'Телефон за връзка',
        }

    def __init__(self, *args, **kwargs):
        super(CreateWalkPlaceForm, self).__init__(*args, **kwargs)
        field_required_error(self.fields.values())

dog_walks/templates/places/create_place_to_eat.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Добави място за хапване{% endblock %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static '/style/forms-style.css' %}">
    <link rel="stylesheet" href="{% static '/style/bluebuttons-style.css' %}">
{% endblock %}
{% block page_content %}
    <div id="read-rules">
        <h2>Преди да създадете място, моля прочетете</h2>
        <a href="{% url 'terms and conditions' %}#create-eat">
            Създаване на място за хапване
        </a>
    </div>
    <div class="form-content">
        <h2>Добавяне на място за хапване достъпно за кучета</h2>
        <form novalidate method="post" action="{% url 'create place to eat' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <p style="color: red">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </p>
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                <div class="user-box">
                    {{ field }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
            {% endfor %}
            <button class="bluebutton" type="submit">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Създай
            </button>
        </form>
    </div>
{% endblock %}

dog_walks/templates/places/create_place_to_sleep.html
{% extends 'base/base.html' %}
{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static '/style/forms-style.css' %}">
    <link rel="stylesheet" href="{% static '/style/bluebuttons-style.css' %}">
{% endblock %}
{% block title %}Добави място за нощувка{% endblock %}
{% block page_content %}
    <div id="read-rules">
        <h2>Преди да създадете място, моля прочетете</h2>
        <a href="{% url 'terms and conditions' %}#create-night">
            Създаване на място за нощувка
        </a>
    </div>
    <div class="form-content">
        <h2>Добавяне на място за нощуване достъпно за кучета</h2>

        <form novalidate method="post" action="{% url 'create place to sleep' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <p style="color: red">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </p>
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                <div class="user-box">
                    {{ field }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
            {% endfor %}
            <button class="bluebutton" type="submit">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Създай
            </button>
        </form>
    </div>
{% endblock %}

dog_walks/templates/places/create_place_to_walk.html
{% extends 'base/base.html' %}
{% load static %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static '/style/forms-style.css' %}">
    <link rel="stylesheet" href="{% static '/style/bluebuttons-style.css' %}">
{% endblock %}
{% block title %}Добави място за разходка{% endblock %}

{% block page_content %}
    <div id="read-rules">
        <h2>Преди да създадете място, моля прочетете</h2>
        <a href="{% url 'terms and conditions' %}#create-walk">
            Създаване на място за разходка
        </a>
    </div>
    <div class="form-content">
        <h2>Добавяне на място за разходка достъпно за кучета</h2>
        <form novalidate method="post" action="{% url 'create place to walk' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <p style="color: red">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </p>
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
                <div class="user-box">
                    {{ field }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
            {% endfor %}
            <button class="bluebutton" type="submit">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                Създай
            </button>
        </form>
    </div>
{% endblock %}

dog_walks/templates/places/eat_details.html
{% extends 'base/places_comments.html' %}
{% block title %}Детайли{% endblock %}
{% block content %}
    <div class="page-container">
        <div class="place-details">
            <h1>{{ object.name }}</h1>
            <ul>
                <li>
                    <strong>Област</strong>
                    <span>{{ object.get_district_display }}</span>
                </li>
                <li>
                    <strong>Населено място</strong>
                    <span>{{ object.city }}</span>
                </li>
                <li>
                    <strong>Вид</strong>
                    <span>{{ object.get_type_display }}</span>
                </li>
                <li>
                    <strong>Ценови диапазон</strong>
                    <span>{{ object.get_price_display }}</span>
                </li>
                <li>
                    <strong>Телефон</strong>
                    {% if object.phone %}
                        <span>{{ object.phone }}</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Уебсайт</strong>
                    {% if object.website %}
                        <span>
                        <a href="{{ object.website }}" rel="nofollow" target="_blank">
                            {{ object.website }}
                        </a>
                        </span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
            </ul>
            <img src="{{ object.image.url }}">
        </div>
        <div class="place-description">
            <h2>Описание</h2>
            <p> {{ object.description }}</p>
            <p class="likes">Любимо място на {{ likes_count }} потребителя</p>

        </div>
        <div class="buttons-container">
            <a title="Сподели" href="#"><i class="fa-solid fa-share-nodes"></i></a>

            {% if is_owner %}
                <a title="Редактирай" href="{% url 'edit eat' pk=object.pk %}"><i class="fa-solid fa-pencil"></i></a>
            {% else %}
                <a title="Докладвай за грешки" href="{% url 'report eat' pk=object.pk %}"><i
                        class="fa-solid fa-flag"></i></a>
                {% if is_user_want_to_visit_place %}
                    <a title="Премахни от Искам да посетя" href="{% url 'want to visit eat' pk=object.pk %}">
                        <i style="font-weight: 600; color:#3586ff" class="fa-solid fa-paw"></i>
                    </a>
                {% else %}
                    <a title="Добави в Искам да посетя" href="{% url 'want to visit eat' pk=object.pk %}">
                        <i class="fa-solid fa-paw"></i>
                    </a>
                {% endif %}
            {% endif %}
            {% if is_user_liked_eat %}
                <a title="Премахни от Любими" href="{% url 'like eat' pk=object.pk %}">
                    <i style="font-weight: 600" class="fa-regular fa-heart"></i>
                </a>
            {% else %}
                <a title="Добави в Любими" href="{% url 'like eat' pk=object.pk %}">
                    <i class="fa-regular fa-heart"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block from_url %}
    <form method="post" action="{% url 'comment eat' pk=object.pk %}">
        {{ comment_form }}
        <button type="submit">Изпрати</button>
        {% csrf_token %}
    </form>
{% endblock %}

dog_walks/templates/places/night_details.html
{% extends 'base/places_comments.html' %}
{% block title %}Детайли{% endblock %}
{% block content %}
    <div class="page-container">
        <div class="place-details">
            <h1>{{ object.name }}</h1>
            <ul>
                <li>
                    <strong>Област</strong>
                    <span>{{ object.get_district_display }}</span>
                </li>
                <li>
                    <strong>Населено място</strong>
                    <span>{{ object.city }}</span>
                </li>
                <li>
                    <strong>Вид</strong>
                    <span>{{ object.get_type_display }}</span>
                </li>
                <li>
                    <strong>Ценови диапазон</strong>
                    <span>{{ object.get_price_display }}</span>
                </li>
                <li>
                    <strong>Брой легла</strong>
                    <span>{{ object.beds_count }}</span>
                </li>
                <li>
                    <strong>Телефон</strong>
                    <span>{{ object.phone }}</span>
                </li>
                <li>
                    <strong>Уебсайт</strong>
                    {% if object.website %}
                        <span>
                        <a href="{{ object.website }}" rel="nofollow" target="_blank">
                            {{ object.website }}
                        </a>
                        </span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Допълнително заплащане за куче</strong>
                    {% if object.dog_fee %}
                        <span>Да</span>
                    {% else %}
                        <span>Не</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Последна редакция</strong>
                    <span>{{ object.modified_date }}</span>
                </li>
            </ul>
            <img src="{{ object.image.url }}">
        </div>
        <div class="place-description">
            <h2>Описание</h2>
            <p> {{ object.description }}</p>
            <p class="likes">Любимо място на {{ likes_count }} потребителя</p>
        </div>
        <div class="buttons-container">
            <a title="Сподели" href="{% url 'share night' pk=object.pk %}"><i class="fa-solid fa-share-nodes"></i></a>
            {% if is_owner %}
                <a title="Редактирай" href="{% url 'edit night' pk=object.pk %}"><i class="fa-solid fa-pencil"></i></a>
            {% else %}
                <a title="Докладвай за грешки" href="{% url 'report night' pk=object.pk %}"><i
                        class="fa-solid fa-flag"></i></a>
                {% if is_user_want_to_visit_place %}
                    <a title="Премахни от Искам да посетя" href="{% url 'want to visit night' pk=object.pk %}">
                        <i style="font-weight: 600; color:#3586ff" class="fa-solid fa-star"></i>
                    </a>
                {% else %}
                    <a title="Добави в Искам да посетя" href="{% url 'want to visit night' pk=object.pk %}">
                        <i class="fa-solid fa-star"></i>
                    </a>
                {% endif %}
            {% endif %}
            {% if is_user_liked_night %}
                <a title="Премахни от Любими" href="{% url 'like night' pk=object.pk %}">
                    <i style="font-weight: 600" class="fa-regular fa-heart"></i>
                </a>
            {% else %}
                <a title="Добави в Любими" href="{% url 'like night' pk=object.pk %}">
                    <i class="fa-regular fa-heart"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block from_url %}
    {% if request.user.profile.have_permission_to_comment %}
        <form method="post" action="{% url 'comment night' pk=object.pk %}">
            {{ comment_form }}
            <button type="submit">Изпрати</button>
            {% csrf_token %}
        </form>
    {% else %}
        <p style="color:red; font-size:20px">Нямате право да коментирате!</p>
    {% endif %}
{% endblock %}

dog_walks/templates/places/walk_details.html
{% extends 'base/places_comments.html' %}
{% block title %}Детайли{% endblock %}
{% block content %}
    <div class="page-container">
        <div class="place-details">
            <h1>{{ object.name }}</h1>
            <ul>
                <li>
                    <strong>Област</strong>
                    <span>{{ object.get_district_display }}</span>
                </li>
                <li>
                    <strong>Населено място</strong>
                    <span>{{ object.city }}</span>
                </li>
                <li>
                    <strong>Вид</strong>
                    <span>{{ object.get_type_display }}</span>
                </li>
                <li>
                    <strong>Телефон</strong>
                    {% if object.phone %}
                        <span>{{ object.phone }}</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Уебсайт</strong>
                    {% if object.website %}
                        <span>
                        <a href="{{ object.website }}" rel="nofollow" target="_blank">
                            {{ object.website }}
                        </a>
                        </span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Позволено за кучета</strong>
                    <span>{{ object.get_dogs_are_welcome_display }}</span>
                </li>
                <li>
                    <strong>difficulty</strong>
                    <span>{{ object.get_difficulty_display }}</span>
                </li>
                <li>
                    <strong>Входна такса</strong>
                    {% if object.entrance_fee %}
                        <span>Да</span>
                    {% else %}
                        <span>Не</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Почивни дни</strong>
                    {% if object.holidays %}
                        <span>{{ object.holidays }}</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>

                <li>
                    <strong>Времетраене</strong>
                    {% if object.duration %}
                        <span>{{ object.duration }} часа</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Разстояние</strong>
                    {% if object.distance %}
                        <span>{{ object.distance }} километра</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>
                <li>
                    <strong>Дениевлация</strong>
                    {% if object.displacement %}
                        <span>{{ object.displacement }} метра</span>
                    {% else %}
                        <span>-</span>
                    {% endif %}
                </li>

            </ul>
            <img src="{{ object.image.url }}">
        </div>
        <div class="place-description">
            <h2>Описание</h2>
            <p> {{ object.description }}</p>
        </div>
        <div class="buttons-container">
            <a title="Сподели" href="#"><i class="fa-solid fa-share-nodes"></i></a>

            {% if is_owner %}
                <a title="Редактирай" href="{% url 'edit walk' pk=object.pk %}"><i class="fa-solid fa-pencil"></i></a>
            {% else %}
                <a title="Докладвай за грешки" href="{% url 'report walk' pk=object.pk %}"><i
                        class="fa-solid fa-flag"></i></a>
                {% if is_user_want_to_visit_place %}
                    <a title="Премахни от Искам да посетя" href="{% url 'want to visit walk' pk=object.pk %}">
                        <i style="font-weight: 600; color:#3586ff" class="fa-solid fa-paw"></i>
                    </a>
                {% else %}
                    <a title="Добави в Искам да посетя" href="{% url 'want to visit walk' pk=object.pk %}">
                        <i class="fa-solid fa-paw"></i>
                    </a>
                {% endif %}
            {% endif %}
            {% if is_user_liked_walk %}
                <a title="Премахни от Любими" href="{% url 'like walk' pk=object.pk %}">
                    <i style="font-weight: 600" class="fa-regular fa-heart"></i>
                </a>
            {% else %}
                <a title="Добави в Любими" href="{% url 'like walk' pk=object.pk %}">
                    <i class="fa-regular fa-heart"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block from_url %}
    <form method="post" action="{% url 'comment walk' pk=object.pk %}">
        {{ comment_form }}
        <button type="submit">Изпрати</button>
        {% csrf_token %}
    </form>
{% endblock %}